name: Docker ECR Deploy

on:
  push:
    branches:
      - Do-06-Hang

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: node-app
  IMAGE_TAG: latest
  BACKEND_API: ${{ secrets.BACKEND_API }}
  BACKEND_PORT: ${{ secrets.BACKEND_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin  ${{ env.ECR_REGISTRY }}
   
    - name: Build and tag Docker image
      id: build-image
      run: |
        docker build --build-arg BACKEND_API="$BACKEND_API" \
         --build-arg BACKEND_PORT="$BACKEND_PORT" \
         -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . \
         -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} 


    - name: Tag and Push Docker image to Amazon ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} 





